package com.dream.forum.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_b_user.USER_ID
     *
     * @mbg.generated
     */
    private BigDecimal userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_b_user.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_b_user.SERIAL_NUMBER
     *
     * @mbg.generated
     */
    private String serialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_b_user.E_MAIL
     *
     * @mbg.generated
     */
    private String eMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tf_b_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_b_user.USER_ID
     *
     * @return the value of tf_b_user.USER_ID
     *
     * @mbg.generated
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_b_user.USER_ID
     *
     * @param userId the value for tf_b_user.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_b_user.USER_NAME
     *
     * @return the value of tf_b_user.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_b_user.USER_NAME
     *
     * @param userName the value for tf_b_user.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_b_user.SERIAL_NUMBER
     *
     * @return the value of tf_b_user.SERIAL_NUMBER
     *
     * @mbg.generated
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_b_user.SERIAL_NUMBER
     *
     * @param serialNumber the value for tf_b_user.SERIAL_NUMBER
     *
     * @mbg.generated
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_b_user.E_MAIL
     *
     * @return the value of tf_b_user.E_MAIL
     *
     * @mbg.generated
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_b_user.E_MAIL
     *
     * @param eMail the value for tf_b_user.E_MAIL
     *
     * @mbg.generated
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }
}