package com.dream.forum.mapper;

import com.dream.forum.entity.User;
import com.dream.forum.entity.UserExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_b_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tf_b_user",
        "where USER_ID = #{userId,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(BigDecimal userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_b_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tf_b_user (USER_ID, USER_NAME, ",
        "SERIAL_NUMBER, E_MAIL)",
        "values (#{userId,jdbcType=DECIMAL}, #{userName,jdbcType=VARCHAR}, ",
        "#{serialNumber,jdbcType=VARCHAR}, #{eMail,jdbcType=VARCHAR})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_b_user
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_b_user
     *
     * @mbg.generated
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_b_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "USER_ID, USER_NAME, SERIAL_NUMBER, E_MAIL",
        "from tf_b_user",
        "where USER_ID = #{userId,jdbcType=DECIMAL}"
    })
    @ResultMap("com.dream.forum.mapper.UserMapper.BaseResultMap")
    User selectByPrimaryKey(BigDecimal userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_b_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_b_user
     *
     * @mbg.generated
     */
    @Update({
        "update tf_b_user",
        "set USER_NAME = #{userName,jdbcType=VARCHAR},",
          "SERIAL_NUMBER = #{serialNumber,jdbcType=VARCHAR},",
          "E_MAIL = #{eMail,jdbcType=VARCHAR}",
        "where USER_ID = #{userId,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(User record);
}