package com.dream.forum.mapper;

import com.dream.forum.entity.User;
import com.dream.forum.entity.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_B_USER
     *
     * @mbg.generated
     */
    @Delete({
        "delete from TF_B_USER",
        "where USER_ID = #{userId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_B_USER
     *
     * @mbg.generated
     */
    @Insert({
        "insert into TF_B_USER (USER_ID, USER_NAME, ",
        "PASSWORD, E_MAIL)",
        "values (#{userId,jdbcType=VARCHAR}, #{userName,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{eMail,jdbcType=VARCHAR})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_B_USER
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_B_USER
     *
     * @mbg.generated
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_B_USER
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "USER_ID, USER_NAME, PASSWORD, E_MAIL",
        "from TF_B_USER",
        "where USER_ID = #{userId,jdbcType=VARCHAR}"
    })
    User selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_B_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_B_USER
     *
     * @mbg.generated
     */
    @Update({
        "update TF_B_USER",
        "set USER_NAME = #{userName,jdbcType=VARCHAR},",
          "PASSWORD = #{password,jdbcType=VARCHAR},",
          "E_MAIL = #{eMail,jdbcType=VARCHAR}",
        "where USER_ID = #{userId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(User record);
}
