server:
  port: 8088
  servlet:
    context-path: /forum

spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/forum?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000

  #服务启动后自动执行配置
  web:
    excute-tool: explorer
    isopenurl: true
    open-url: http://localhost:${server.port}/forum/swagger-ui.html

mybatis:
  config-location: classpath:mybatis-config.xml
