server:
  port: 8088
  servlet:
    context-path: /forum

spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://39.106.137.255:3306/selfdb?useUnicode=true&characterEncoding=utf8
    username: dev
    password: 123456

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000

  #服务启动后自动执行配置
  web:
    excute-tool: explorer
    isopenurl: true
    open-url: http://localhost:${server.port}/forum/swagger-ui.html

mybatis:
  config-location: classpath:mybatis-config.xml
